### ISSUE TITLE
What does LongestPrefix do?

### ISSUE THREAD

**Issue by aletheia7** [k-sone/critbitgo#6]
If I Insert() the following keys:
```
/hi/bye/why
/hi/bye
/hi
```
LongestPrefix(/hi) will output /hi. I am expecting /hi/bye/why from the description.

Why is /hi the longest prefix?

**Comment by k-sone** [comment]
This is what I intended. Returns the key that following conditions:
- The key that matches the prefix of the given string
- The key with the longest matching part
- If there are multiple results, the nearest key in lexicographic

Examples:
```
LongestPrefix("/hi")                 // Output: "/hi"
LongestPrefix("/hi/hoge")            // Output: "/hi"
LongestPrefix("/hi/bye/hoge")        // Output: "/hi/bye"
LongestPrefix("/hi/bye/why/hoge")    // Output: "/hi/bye/why"
```

**Comment by aletheia7** [comment]
Thanks
